# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: SAP Fiori Demo

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Cloud Foundry
      uses: jhunt/cf-push@v1
      with:
        api: ${{ secrets.CF_API }}
        org: ${{ secrets.CF_ORG }}
        space: ${{ secrets.CF_SPACE }}
        username: ${{ secrets.CF_USERNAME }}
        password: ${{ secrets.CF_PASSWORD }}
        manifest: manifest.yml
        validate: false